### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by j-mueller** [Cirex/atom-metro-ui#12]
Steps to reproduce:
1. Open a folder in atom 
2. Error appears immediately

This happens also if I use the metro-ui theme. Please let me know if you need any more information

**Atom Version**: 1.0.7
**System**: Microsoft Windows 10 Pro
**Thrown From**: [metro-ui](https://github.com/Cirex/atom-metro-ui) package, v2.2.2
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\User\.atom\packages\metro-ui\node_modules\winreg\lib\registry.js:351

TypeError: undefined is not a function
  at ChildProcess.<anonymous> (C:\Users\User\.atom\packages\metro-ui\node_modules\winreg\lib\registry.js:351:35)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at maybeClose (child_process.js:997:16)
  at Socket.<anonymous> (child_process.js:1166:11)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "metro-ui",
      "base16-tomorrow-dark-theme"
    ],
    "autoHideMenuBar": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-html-preview, v0.1.11
atomatigit, v1.5.4
autocomplete-haskell, v0.4.5
haskell-ghc-mod, v0.8.9
html-entities, v0.4.0
ide-haskell, v0.7.1
language-diff, v0.3.1
language-groovy, v0.4.0
language-haskell, v1.3.1
language-json5, v1.1.0
language-latex, v0.6.1
language-lua, v0.9.4
language-scala, v1.1.3
language-thrift, v1.0.1
metro-ui, v2.2.2
pretty-json, v0.4.1
react, v0.12.6
recent-projects, v0.8.3
symbol-gen, v1.0.0

# Dev
No dev packages
```

**Comment by Cirex** [comment]
This looks more like a **winreg** bug then a **metro-ui** bug, but I'll look into it when I can and see if I can't figure out what's causing it to trip up on your end.

In the mean time, you should be able to uncheck `Use System Accent Color` to make the error go away.

**Comment by j-mueller** [comment]
Thank you, that fixes it!

**Comment by Cirex** [comment]
It doesn't technically fix it. It's disabling the offending code which means it will no longer try to pull your accent color from your Windows 10 settings. You can set your theme accent color manually at least for the time being.

I believe you might have something about your Windows installation which **winreg** doesn't account for. So rather then returning the error parameter as I would expect it to it's throwing the unhandled exception.

I should have some time this weekend to dig into it and see if I can find the root of the problem.

**Comment by j-mueller** [comment]
I'm aware that it doesn't technically fix it, sorry for using the wrong word here. And thank you for looking into it more!
