### ISSUE TITLE
Error compiling Less stylesheet using New Moon syntax 

### ISSUE THREAD

**Issue by ryanspice** [Cirex/atom-metro-ui#20]
https://github.com/taniarascia/new-moon-atom-syntax

```
Error compiling Less stylesheet: D:\Programs\Atom\resources\app.asar\static\atom.less
Line number: 38
error evaluating function `fadeout`: color.toHSL is not a function
```

everything seems to be fine, but if I restart I get a white screen and this error in the console that pops up:

```
Error
    at new Parser (D:\Programs\Atom\resources\app.asar\node_modules\less-cache\node_modules\less\lib\less\parser.js:333:27)
    at LessCache.module.exports.LessCache.parseLess (D:\Programs\Atom\resources\app.asar\node_modules\less-cache\lib\less-cache.js:244:16)
    at LessCache.module.exports.LessCache.cssForFile (D:\Programs\Atom\resources\app.asar\node_modules\less-cache\lib\less-cache.js:275:20)
    at LessCache.module.exports.LessCache.readFileSync (D:\Programs\Atom\resources\app.asar\node_modules\less-cache\lib\less-cache.js:263:19)
    at LessCompileCache.module.exports.LessCompileCache.read (D:\Programs\Atom\resources\app.asar\src\less-compile-cache.js:36:25)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (D:\Programs\Atom\resources\app.asar\src\theme-manager.js:310:33)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (D:\Programs\Atom\resources\app.asar\src\theme-manager.js:286:21)
    at ThemeManager.module.exports.ThemeManager.requireStylesheet (D:\Programs\Atom\resources\app.asar\src\theme-manager.js:203:24)
    at ThemeManager.module.exports.ThemeManager.reloadBaseStylesheets (D:\Programs\Atom\resources\app.asar\src\theme-manager.js:266:12)
    at ThemeManager.module.exports.ThemeManager.loadBaseStylesheets (D:\Programs\Atom\resources\app.asar\src\theme-manager.js:261:19)
```

**Comment by martindevans** [comment]
I get a very similar error using the [duotone dark syntax](https://atom.io/themes/duotone-dark-syntax). If I remove the .atom/packages/metro-ui directory atom loads just fine, if not I get a white screen and the developer tools.

```
Error compiling Less stylesheet: `C:\Users\Martin\AppData\Local\atom\app-1.6.2\resources\app.asar\static\atom.less`
Line number: 93
error evaluating function `lighten`: color.toHSL is not a function
```

```
Error
    at new Parser (C:\Users\Martin\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\less-cache\node_module…:333)
    at LessCache.module.exports.LessCache.parseLess (C:\Users\Martin\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\less-cache\lib\less-ca…:255)
    at LessCache.module.exports.LessCache.cssForFile (C:\Users\Martin\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\less-cache\lib\less-ca…:286)
    at LessCache.module.exports.LessCache.readFileSync (C:\Users\Martin\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\less-cache\lib\less-ca…:274)
    at LessCompileCache.module.exports.LessCompileCache.read (C:\Users\Martin\AppData\Local\atom\app-1.6.2\resources\app.asar\src\less-compile-cache.js:36)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (C:\Users\Martin\AppData\Local\atom\app-1.6.2\resources\app.asar\src\theme-manager.js:281)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (C:\Users\Martin\AppData\Local\atom\app-1.6.2\resources\app.asar\src\theme-manager.js:257)
    at ThemeManager.module.exports.ThemeManager.requireStylesheet (C:\Users\Martin\AppData\Local\atom\app-1.6.2\resources\app.asar\src\theme-manager.js:174)
    at ThemeManager.module.exports.ThemeManager.reloadBaseStylesheets (C:\Users\Martin\AppData\Local\atom\app-1.6.2\resources\app.asar\src\theme-manager.js:237)
    at ThemeManager.module.exports.ThemeManager.loadBaseStylesheets (C:\Users\Martin\AppData\Local\atom\app-1.6.2\resources\app.asar\src\theme-manager.js:232)
    at new AtomEnvironment (C:\Users\Martin\AppData\Local\atom\app-1.6.2\resources\app.asar\src\atom-environment.js:250)
    at module.exports (C:\Users\Martin\AppData\Local\atom\app-1.6.2\resources\app.asar\src\initialize-application-window.js:19)
    at setupWindow (index.js:86)
    at window.onload (index.js:41)
```
