### ISSUE TITLE
Uncaught TypeError: lines[line].trim is not a function

### ISSUE THREAD

**Issue by dillonma** [Cirex/atom-metro-ui#21]
Just installed and switched to the theme ...

**Atom Version**: 1.3.3
**System**: Microsoft Windows 10 Pro
**Thrown From**: [metro-ui](https://github.com/Cirex/atom-metro-ui) package, v2.2.2
### Stack Trace

Uncaught TypeError: lines[line].trim is not a function

```
At C:\Users\Dillon\.atom\packages\metro-ui\node_modules\winreg\lib\registry.js:351

TypeError: lines[line].trim is not a function
    at ChildProcess.<anonymous> (C:\Users\Dillon\.atom\packages\metro-ui\node_modules\winreg\lib\registry.js:351:35)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
  6x -7:15.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:05.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -7:05.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -7:04.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -7:02.9.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -7:02.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -7:02.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -6:31.3.0 core:save (atom-text-editor.editor.is-focused)
     -5:23.7.0 window:toggle-full-screen (atom-text-editor.editor.is-focused)
     -5:20 latex:build (atom-text-editor.editor.is-focused)
     -2:30.3.0 editor:toggle-soft-wrap (atom-text-editor.editor.is-focused)
     -2:24.6.0 settings-view:open (atom-text-editor.editor.is-focused)
 15x -2:17.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -2:12.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:19.2.0 core:delete (atom-text-editor.editor.mini.is-focused)
  3x -0:56.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "metro-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
bottom-dock, v0.3.7
language-latex, v0.6.1
latex, v0.28.2
latex-autocomplete, v0.2.4
latexer, v0.2.7
linter, v1.11.3
linter-just-say-no, v0.6.0
linter-manager, v0.2.8
linter-scspell, v2.0.1
linter-write-good, v0.6.1
metro-ui, v2.2.2
minimap, v4.19.0
minimap-linter, v1.1.1
pdf-view, v0.39.0
typewriter, v0.3.5

# Dev
No dev packages
```

**Comment by dillonma** [comment]
Just realized it's happening across multiple themes. Something on my end.
